export var INGREDIENTS = [
    {id: '1', description: 'mit Farbstoff'},
    {id: '2', description: 'mit Konservierungsstoff'},
    {id: '3', description: 'mit Antioxidationsmittel'},
    {id: '4', description: 'mit Geschmacksverstärker'},
    {id: '5', description: 'geschwefelt'},
    {id: '6', description: 'geschwärzt'},
    {id: '7', description: 'gewachst'},
    {id: '8', description: 'mit Phosphat'},
    {id: '9', description: 'mit Süßungsmittel'},
    {id: '10', description: 'eine Phenylalaninquelle'},
    {id: '13', description: 'kann die Aktivität und Aufmerksamkeit von Kindern beeinträchtigen'},
    {id: '14', description: 'mit kakaohaltiger Fettglasur'},
    {id: '15', description: 'koffeinhaltig'},
    {id: '16', description: 'chininhaltig'},
    {id: 'Gl', description: 'Gluten'},
    {id: 'Wz', description: 'Weizen'},
    {id: 'Ro', description: 'Roggen'},
    {id: 'Gs', description: 'Gerste'},
    {id: 'Hf', description: 'Hafer'},
    {id: 'Di', description: 'Dinkel'},
    {id: 'Ka', description: 'Kamut (Khorasan-Weizen)'},
    {id: 'Er', description: 'Erdnüsse'},
    {id: 'Nu', description: 'Schalenfrüchte'},
    {id: 'Ma', description: 'Mandeln'},
    {id: 'Ha', description: 'Haselnüsse'},
    {id: 'Wa', description: 'Walnüsse'},
    {id: 'Ca', description: 'Cashewnüsse'},
    {id: 'Pe', description: 'Pekannüsse'},
    {id: 'Pa', description: 'Paranüsse'},
    {id: 'Pi', description: 'Pistazien'},
    {id: 'Mc', description: 'Macadamianüsse'},
    {id: 'Kr', description: 'Krebstiere'},
    {id: 'Ei', description: 'Hühnerei'},
    {id: 'Fi', description: 'Fisch'},
    {id: 'So', description: 'Soja'},
    {id: 'Mi', description: 'Milch- und Milchzucker'},
    {id: 'Sel', description: 'Sellerie'},
    {id: 'Sen', description: 'Senf'},
    {id: 'Ses', description: 'Sesam'},
    {id: 'Su', description: 'Schwefeloxid/Sulfite'},
    {id: 'Lu', description: 'Lupine'},
    {id: 'We', description: 'Weichtiere'},
    {id: 'A', description: 'Alkohol'},
    {id: 'F', description: 'Fisch'},
    {id: 'G', description: 'Geflügel'},
    {id: 'K', description: 'Knoblauch'},
    {id: 'L', description: 'Lammfleisch'},
    {id: 'R', description: 'Rindfleisch'},
    {id: 'S', description: 'Schweinefleisch'},
    {id: 'W', description: 'Wildfleisch'},
    {id: 'T1', description: 'tierische Gelatine'},
    {id: 'T2', description: 'tierisches Lab'},
    {id: 'T3', description: 'echtes Karmin'},
    {id: 'T4', description: 'Sepia'},
    {id: 'T5', description: 'Honig'},
    {id: 'V', description: 'Vegetarische Speisen'},
    {id: 'V*', description: 'Vegane Speisen'}
  ];